name: build
on:
  push:
    branches:
      - 'master'

permissions:
  id-token: write
  packages: write

jobs:
  setup_env:
    name: ⚙️ Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA::7}`" >> $GITHUB_ENV

      - name: Put commit msg in environment
        run: echo "COMMIT_MSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Escape commit message
        run: |
          echo "COMMIT_MSG=$(echo $COMMIT_MSG | tr -d \'\\\")" >> $GITHUB_ENV

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    outputs:
      short_sha: ${{ env.SHORT_SHA }}
      commit_msg: ${{ env.COMMIT_MSG }}
      branch_name: ${{ env.BRANCH_NAME }}

  build:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.0'

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Update go deps
        run: go mod tidy

      - name: install go mock
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: install go-junit
        run: go get -u github.com/jstemmer/go-junit-report

      - name: run tests
        run: make test

      - name: build executable
        run: make build; ls; ls bin

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: generate tag
        run: |-
          export PROJ_VERSION="1.0.9"
          echo "Project Version: $PROJ_VERSION"
          echo "TAG=$PROJ_VERSION-$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "SHORT_TAG=$PROJ_VERSION" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: '.'
          push: true
          platforms: linux/amd64,linux/arm64
          tags: unbindapp/kube-oidc-proxy:${{ needs.setup_env.outputs.branch_name }}-${{ env.GITHUB_RUN_ID }}
